# Intro

In [1]:
import numpy as np

In [11]:
z = np.empty(0)
z
#Creating an empty array

array([], dtype=float64)

In [12]:
a = np.array([25,36,49,81,9,64])
a

array([25, 36, 49, 81,  9, 64])

In [13]:
a[0]

25

In [14]:
a.itemsize
# o/p: size of 1 element

4

In [15]:
a.size
#o/p: total lenth (ie no. of elements) of array

6

In [16]:
a.ndim
#o/p dimension of a

1

In [17]:
a.reshape(3,2)

array([[25, 36],
       [49, 81],
       [ 9, 64]])

# slicing

In [18]:
##In numpy indexing of row and column starts from 0th position. 3*3 matrix has 0th,1st and 2nd row awa column respectively.

In [19]:
b = np.array([[3,4,5], [1,2,14], [7,8,9]])

In [20]:
b

array([[ 3,  4,  5],
       [ 1,  2, 14],
       [ 7,  8,  9]])

In [21]:
b.ndim

2

In [22]:
b[0]
#prints first row

array([3, 4, 5])

In [23]:
b[-1]
#prints last row

array([7, 8, 9])

In [24]:
b[0,2]
#o/p will be element at 0th row and 2nd column ie 5

5

In [25]:
b[0:2,2]
#o/p will be elemnts from 0th &1st row(since in indexing we exclude RHS no.) and 2nd column

array([ 5, 14])

In [26]:
for row in b:
    print(row)
#for printing row

[3 4 5]
[ 1  2 14]
[7 8 9]


In [27]:
for cell in b.flat:
    print(cell)
#for printing elements in flattened way.

3
4
5
1
2
14
7
8
9


In [28]:
##another USELESS way to print elements:
for row in b:
    for cell in row:
        print(cell)

3
4
5
1
2
14
7
8
9


# iterate

In [29]:
#2 USEFUL way to print elements:

In [30]:
for x in np.nditer(b, order='C'):
    print(x)
#use capital C. This is called as C order. 
#It gives flatten o/p but row wise. ie print row 0th first, then go for 1st row and likewise

3
4
5
1
2
14
7
8
9


In [31]:
b

array([[ 3,  4,  5],
       [ 1,  2, 14],
       [ 7,  8,  9]])

In [32]:
for x in np.nditer(b, order='F'):
    print(x)
#This is called as Fortran Order. 
#It gives flatten  o/p but column wise. ie prints 0th column first, then go for 1st column and likewise

3
1
7
4
2
8
5
14
9


In [33]:
for x in np.nditer(b,op_flags=['readwrite']):
    x[...]=x*x
print(b)
#for rewriting elements in array. if we write x[...]=2*x, then all elements will be multiplied by 2

[[  9  16  25]
 [  1   4 196]
 [ 49  64  81]]


In [34]:
#iterate 2 arrays: condition for iteration: 2 arrays should be of equal length or one of them should be 1.

In [35]:
b

array([[  9,  16,  25],
       [  1,   4, 196],
       [ 49,  64,  81]])

In [36]:
c=np.arange(12,19,3).reshape(3,1)

In [37]:
c

array([[12],
       [15],
       [18]])

In [38]:
for x,y in np.nditer([b,c]): 
     print(x,y)
#array b ke 0th row k elements khatam hone tak array c ka 0th element hi chalta rahega. ie 9~12,16~12,25~12...

9 12
16 12
25 12
1 15
4 15
196 15
49 18
64 18
81 18


# To intialize array with all zeroes, we use np.zeros fn! np.zeros((shape))

In [39]:
print(np.zeros((2,3))) #2 is no. of rows & 3 is no. of columns.


[[0. 0. 0.]
 [0. 0. 0.]]


In [40]:
print(np.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [41]:
print(np.empty((3,4)))
#Creating a empty array 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [42]:
print(np.full([5,3], 95))
#Creating a full array 

[[95 95 95]
 [95 95 95]
 [95 95 95]
 [95 95 95]
 [95 95 95]]


# Different operations:

In [43]:
print(np.sqrt(a))

[5. 6. 7. 9. 3. 8.]


In [44]:
print(np.std(a)) #std deviation of array b

23.958297101421877


In [45]:
print(np.sum(a))

264


In [46]:
b

array([[  9,  16,  25],
       [  1,   4, 196],
       [ 49,  64,  81]])

In [47]:
print(b.sum(axis = 0)) #axis=0 means column. hence it gave columnwise sum ie 9+1+49=59 likewsie

[ 59  84 302]


In [49]:
print(b.sum(axis = 1)) #axis=1 means row. hence it gave rowwise sum ie 9+16+25=50 likewise

[ 50 201 194]


In [4]:
np.argmax([2,43,12,35,87])
#4 means 4th index, ie 87. Argmax gives index of max value we have in list.

4

# Range fn:

In [50]:
print(np.arange(5))

[0 1 2 3 4]


In [51]:
print(np.arange(6).reshape(2,3))

[[0 1 2]
 [3 4 5]]


In [52]:
print(np.arange(4,9))

[4 5 6 7 8]


In [77]:
print(np.arange(9,21,3)) #from 9 to 20 with gap of 2 in between them.

[ 9 12 15 18]


In [53]:
print(np.arange(9,2,-1)) #from 9 to 2, -1 means reverse.

[9 8 7 6 5 4 3]


In [54]:
print(np.arange(19,4,-2)) #from 19 to 4 in reverse with gap of 1 in between them.

[19 17 15 13 11  9  7  5]


In [55]:
b = np.array([[3,4,5], [1,2,14], [7,8,9]])

In [56]:
b

array([[ 3,  4,  5],
       [ 1,  2, 14],
       [ 7,  8,  9]])

In [57]:
d = np.array([[73,54,56], [31,22,14], [27,8,19]])

In [58]:
d

array([[73, 54, 56],
       [31, 22, 14],
       [27,  8, 19]])

In [78]:
print(np.vstack([b,d])) #vertical stacking

[[ 3  4  5]
 [ 1  2 14]
 [ 7  8  9]
 [73 54 56]
 [31 22 14]
 [27  8 19]]


In [81]:
print(np.hstack([b,d])) #horizontal stacking

[[ 3  4  5 73 54 56]
 [ 1  2 14 31 22 14]
 [ 7  8  9 27  8 19]]


In [61]:
e = np.arange(24).reshape(4,6) #popular method for writing array of continuous numers.

In [62]:
e

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [63]:
print(np.hsplit(e,2)) #to split an array into multiple sub-arrays horizontally (column-wise).
#hsplit is equivalent to split with axis=1

[array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]]), array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23]])]


In [64]:
f = np.hsplit(e,2) #Alternative way, so that we can use o/p as a variable.

In [65]:
print(f[0]) #f[0],f[1] can be used as variables

[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]
 [18 19 20]]


In [66]:
print(np.vsplit(e,2)) #to split an array into multiple sub-arrays vertically (row-wise).
#vsplit is equivalent to split with axis=0 (default)

[array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])]


In [67]:
g = np.arange(12).reshape(4,3) #popular method for writing array of continuous numers.

In [68]:
g

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [69]:
h = g>6

In [70]:
h #gives boolean o/p.

array([[False, False, False],
       [False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [71]:
g[h]
#o/p: only those values which satisfy condition given in h function. technique is useful for extracting data from an array.

array([ 7,  8,  9, 10, 11])

In [72]:
g[h]=0
#it is used to replace those values which satisfy condition given in g function. here we replaced with 0.

In [73]:
g

array([[0, 1, 2],
       [3, 4, 5],
       [6, 0, 0],
       [0, 0, 0]])

##Normal distribution:

#x = np.random.normal(loc=(), scale=(), size=())
#Loc: Mean of the distribution.
#Scale: Standard deviation of the distribution
#Size: Output shape. It is optional. Defualt o/p shape is array, of given no. of elements, eg:8. If eg:(2,3) is provided, then o/p shape will be 2*3 matrix. If eg:(2,3,2) is provided, then o/p shape will be 2 matrixes of size 2*3. 

In [75]:
x = np.random.normal(170, 10, 8)
x

array([171.26413642, 187.5932371 , 165.97149293, 171.45003471,
       155.77675969, 171.2227657 , 167.83064838, 188.41780741])

Tip: In jupyter, go on any function and press Shift+Tab, it will open documentation of that function.